"""add last message timestamp to chat

Revision ID: 218cf6793f08
Revises: a21dc8b68504
Create Date: 2026-09-04 10:26:29.724093

"""
from alembic import op
import sqlalchemy as sa

import custom_types.utc_datetime

# revision identifiers, used by Alembic.
revision = '218cf6793f08'
down_revision = 'a21dc8b68504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_at', custom_types.utc_datetime.UTCDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('last_message_at')

    # ### end Alembic commands ###
