"""add index to chat last message at

Revision ID: 63f2eb40e7dc
Revises: 218cf6793f08
Create Date: 2026-09-04 10:28:10.716274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f2eb40e7dc'
down_revision = '218cf6793f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_last_message_at'), ['last_message_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_last_message_at'))

    # ### end Alembic commands ###
