"""create chat tables

Revision ID: 8858141dea8c
Revises: 
Create Date: 2026-09-02 17:41:53.268163

"""
from alembic import op
import sqlalchemy as sa

import custom_types.uuid
import custom_types.utc_datetime

# revision identifiers, used by Alembic.
revision = '8858141dea8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', custom_types.uuid.UUIDType(length=36), nullable=False),
    sa.Column('created_at', custom_types.utc_datetime.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', custom_types.uuid.UUIDType(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', custom_types.utc_datetime.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_participant',
    sa.Column('chat_id', custom_types.uuid.UUIDType(length=36), nullable=False),
    sa.Column('user_id', custom_types.uuid.UUIDType(length=36), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_table('message',
    sa.Column('id', custom_types.uuid.UUIDType(length=36), nullable=False),
    sa.Column('chat_id', custom_types.uuid.UUIDType(length=36), nullable=False),
    sa.Column('sender_id', custom_types.uuid.UUIDType(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', custom_types.utc_datetime.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('chat_participant')
    op.drop_table('user')
    op.drop_table('chat')
    # ### end Alembic commands ###
